/*----- PROTECTED REGION ID(TangoSnmp::DynAttrUtils.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TangoSnmpDynAttrUtils.cpp
//
// description : Dynamic attributes utilities file for the TangoSnmp class
//
// project :     Tango<-->Snmp link
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TangoSnmp.h>
#include <TangoSnmpClass.h>

/*----- PROTECTED REGION END -----*/	//	TangoSnmp::DynAttrUtils.cpp

//================================================================
//  Attributes managed is:
//================================================================
//================================================================

//	For compatibility reason, this file (TangoSnmpDynAttrUtils)
//	manage also the dynamic command utilities.
//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  Simulate      |  simulate
//================================================================

namespace TangoSnmp_ns
{
//=============================================================
//	Add/Remove dynamic attribute methods
//=============================================================



//============================================================
//	Tool methods to get pointer on attribute data buffer 
//============================================================


//=============================================================
//	Add/Remove dynamic command methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a Simulate dynamic command.
 *
 *  parameter cmdname: command name to be cretated and added.
 *  parameter device:  Set this flag to true if the command must be added for only this device.
 */
//--------------------------------------------------------
void TangoSnmp::add_Simulate_dynamic_command(string cmdname, bool device)
{
	SimulateClass	*pSimulateCmd =
		new SimulateClass(cmdname.c_str(),
			Tango::DEV_BOOLEAN, Tango::DEV_VOID,
			"Enable simulation?",
			"",
			Tango::EXPERT);
	add_command(pSimulateCmd, device);
}
//--------------------------------------------------------
/**
 *	remove a Simulate dynamic command.
 *
 *  parameter cmdname: command name to be removed.
 */
//--------------------------------------------------------
void TangoSnmp::remove_Simulate_dynamic_command(string cmdname)
{
	remove_command(cmdname, true);
}

} //	namespace
