version: '2.2'

services:
  dsconfig:
    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dsconfig
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - NETWORK_MODE=${NETWORK_MODE}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             ls -la dsconfig &&
             if [ \"${NETWORK_MODE}\" != \"host\" ]; then sed -i 's/127.0.0.1/${CONTAINER_NAME_PREFIX}tester/g' dsconfig/db.json; fi &&
             json2tango -w -a dsconfig/db.json && sleep infinity"
             # sed is used to replace hard-coded IP (works on local PC) 
             #  with docker network reference to run on CI
             #
             # json2tango parameters:
             # -w write to database
             # -u update (use to not delete stuff)
             # -a ???
    volumes:
      - ./dsconfig:/dsconfig

  ds:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tangosnmp:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}ds
    depends_on:
      - dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             retry --max=5 && \
             if [ -d /root/.snmp/mibs ]; then echo 'found mibs' && ls -la /root/.snmp/mibs ; else echo 'no mibs!'; fi && \
             TangoSnmp andrew"
    volumes_from:
      - rsyslog:rw
    volumes:
      - ./mibs:/root/.snmp/mibs

  rsyslog: 
    image: jumanjiman/rsyslog
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog
    network_mode: ${NETWORK_MODE}

  tester:
    image: nexus.engageska-portugal.pt/ska-docker/tangosnmp-tester:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tester
    depends_on:
      - databaseds
      - ds
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - NETWORK_MODE=${NETWORK_MODE}
    command: >
        sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
        retry --max=5 &&
        if [ \"${NETWORK_MODE}\" = \"host\" ]; then LISTEN=127.0.0.1; else LISTEN=\"${CONTAINER_NAME_PREFIX}tester\"; fi &&
        echo SNMP simulator will listen at $${LISTEN} && 
        ( (python -c 'import tango' && echo python has tango) || echo python no tango ) &&
        snmpsimd.py --data-dir=. --agent-udpv4-endpoint=$${LISTEN}\:1024"

# notes for tester command: 
#  double $ to prevent docker from trying to evaulate LISTEN
#  backslash-colon to prevent docker/yaml confusion (very cryptic errors)
